AWSTemplateFormatVersion: '2010-09-09'

Description: Bucket S3 criado com AWS CloudFormation

Resources:
  MeuBucketS3:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled